// <auto-generated />
using System;
using Imagein.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Imagein.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181027111302_AddPhysicalName")]
    partial class AddPhysicalName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Imagein.Entity.Entities.FileEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(39)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CAST(NOW() at time zone 'utc' AS timestamp)");

                    b.Property<string>("Description");

                    b.Property<int>("FileStoreType");

                    b.Property<string>("MimeType");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<string>("PhysicalName");

                    b.Property<int>("Size");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CAST(NOW() at time zone 'utc' AS timestamp)");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
